# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftExample
  pod 'RxSwift', '5.1.1'
   pod 'RxCocoa', '5.1.1'

  target 'RxSwiftExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '5.1.1'
    pod 'RxTest', '5.1.1'
  end

  target 'RxSwiftExampleUITests' do
    # Pods for testing
  end

end
